language: node_js
services:
  - docker
node_js:
  - 10
before_script:
  - npm ci --no-optional
cache:
  directories:
  - "$HOME/.npm"
script:
  - docker run -it --rm -v $(pwd):$(pwd) -w $(pwd) --entrypoint="npm" cypress/included:3.6.1 run test:e2e
